export { ProjectCard } from './ui/ProjectCard'
export { ProjectDetails } from './ui/ProjectDetails'
export { ProjectThumbnail } from './ui/ProjectThumbnail'
export type { Project, ProjectThumbnailSource } from './model/types'
export { PROJECTS_DATA } from './model/projects.data'
